# will anonomous fns work?

void call(([num] -> num) cb, num arg) {
    print(cb(arg))
}

num main() {
    call((num arg) -> num {
        print('doubling!')
        return arg * 2  # double trouble
    }, 5)

    return 0
}
